/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface AdVideo {
  'id' : AdVideoId,
  'title' : string,
  'active' : boolean,
  'video' : ExternalBlob,
}
export type AdVideoId = bigint;
export interface Category { 'id' : CategoryId, 'name' : string }
export type CategoryId = bigint;
export interface DeliveryAgent {
  'id' : DeliveryAgentId,
  'name' : string,
  'phone' : string,
}
export type DeliveryAgentId = bigint;
export type ExternalBlob = Uint8Array;
export interface Order {
  'id' : OrderId,
  'customerName' : string,
  'status' : OrderStatus,
  'paymentMethod' : { 'cod' : null } |
    { 'upi' : { 'transactionId' : string } },
  'customerPhone' : string,
  'createdAt' : Time,
  'totalAmount' : bigint,
  'address' : string,
  'items' : Array<OrderItem>,
  'deliveryAgent' : [] | [DeliveryAgentId],
}
export type OrderId = bigint;
export interface OrderItem {
  'productId' : ProductId,
  'quantity' : bigint,
  'price' : bigint,
}
export type OrderStatus = { 'shipped' : null } |
  { 'cancelled' : null } |
  { 'pending' : null } |
  { 'outForDelivery' : null } |
  { 'delivered' : null } |
  { 'confirmed' : null } |
  { 'processing' : null };
export interface Product {
  'id' : ProductId,
  'name' : string,
  'description' : string,
  'stock' : bigint,
  'category' : CategoryId,
  'image' : ExternalBlob,
  'price' : bigint,
}
export type ProductId = bigint;
export type Time = bigint;
export interface UserProfile {
  'name' : string,
  'address' : string,
  'phone' : string,
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _CaffeineStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _CaffeineStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _CaffeineStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface _SERVICE {
  '_caffeineStorageBlobIsLive' : ActorMethod<[Uint8Array], boolean>,
  '_caffeineStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_caffeineStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_caffeineStorageCreateCertificate' : ActorMethod<
    [string],
    _CaffeineStorageCreateCertificateResult
  >,
  '_caffeineStorageRefillCashier' : ActorMethod<
    [[] | [_CaffeineStorageRefillInformation]],
    _CaffeineStorageRefillResult
  >,
  '_caffeineStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addAdVideo' : ActorMethod<[string, ExternalBlob, boolean], AdVideoId>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'assignOrderToAgent' : ActorMethod<[OrderId, DeliveryAgentId], undefined>,
  'createCategory' : ActorMethod<[string], CategoryId>,
  'createDeliveryAgent' : ActorMethod<[string, string], DeliveryAgentId>,
  'createProduct' : ActorMethod<
    [string, string, bigint, CategoryId, bigint, ExternalBlob],
    ProductId
  >,
  'deleteProduct' : ActorMethod<[ProductId], undefined>,
  'getActiveAdVideos' : ActorMethod<[], Array<AdVideo>>,
  'getAdVideos' : ActorMethod<[], Array<AdVideo>>,
  'getAllProducts' : ActorMethod<[], Array<Product>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getCategories' : ActorMethod<[], Array<Category>>,
  'getDeliveryAgents' : ActorMethod<[], Array<DeliveryAgent>>,
  'getOrder' : ActorMethod<[OrderId], Order>,
  'getOrdersByPhone' : ActorMethod<[string], Array<Order>>,
  'getProduct' : ActorMethod<[ProductId], Product>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'placeOrder' : ActorMethod<
    [
      string,
      string,
      string,
      Array<OrderItem>,
      bigint,
      { 'cod' : null } |
        { 'upi' : { 'transactionId' : string } },
    ],
    OrderId
  >,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'updateOrderStatus' : ActorMethod<[OrderId, OrderStatus], undefined>,
  'updateProduct' : ActorMethod<
    [ProductId, string, string, bigint, CategoryId, bigint, ExternalBlob],
    undefined
  >,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];