/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _CaffeineStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _CaffeineStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _CaffeineStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const ExternalBlob = IDL.Vec(IDL.Nat8);
export const AdVideoId = IDL.Nat;
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const OrderId = IDL.Nat;
export const DeliveryAgentId = IDL.Nat;
export const CategoryId = IDL.Nat;
export const ProductId = IDL.Nat;
export const AdVideo = IDL.Record({
  'id' : AdVideoId,
  'title' : IDL.Text,
  'active' : IDL.Bool,
  'video' : ExternalBlob,
});
export const Product = IDL.Record({
  'id' : ProductId,
  'name' : IDL.Text,
  'description' : IDL.Text,
  'stock' : IDL.Nat,
  'category' : CategoryId,
  'image' : ExternalBlob,
  'price' : IDL.Nat,
});
export const UserProfile = IDL.Record({
  'name' : IDL.Text,
  'address' : IDL.Text,
  'phone' : IDL.Text,
});
export const Category = IDL.Record({ 'id' : CategoryId, 'name' : IDL.Text });
export const DeliveryAgent = IDL.Record({
  'id' : DeliveryAgentId,
  'name' : IDL.Text,
  'phone' : IDL.Text,
});
export const OrderStatus = IDL.Variant({
  'shipped' : IDL.Null,
  'cancelled' : IDL.Null,
  'pending' : IDL.Null,
  'outForDelivery' : IDL.Null,
  'delivered' : IDL.Null,
  'confirmed' : IDL.Null,
  'processing' : IDL.Null,
});
export const Time = IDL.Int;
export const OrderItem = IDL.Record({
  'productId' : ProductId,
  'quantity' : IDL.Nat,
  'price' : IDL.Nat,
});
export const Order = IDL.Record({
  'id' : OrderId,
  'customerName' : IDL.Text,
  'status' : OrderStatus,
  'paymentMethod' : IDL.Variant({
    'cod' : IDL.Null,
    'upi' : IDL.Record({ 'transactionId' : IDL.Text }),
  }),
  'customerPhone' : IDL.Text,
  'createdAt' : Time,
  'totalAmount' : IDL.Nat,
  'address' : IDL.Text,
  'items' : IDL.Vec(OrderItem),
  'deliveryAgent' : IDL.Opt(DeliveryAgentId),
});

export const idlService = IDL.Service({
  '_caffeineStorageBlobIsLive' : IDL.Func(
      [IDL.Vec(IDL.Nat8)],
      [IDL.Bool],
      ['query'],
    ),
  '_caffeineStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_caffeineStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_CaffeineStorageCreateCertificateResult],
      [],
    ),
  '_caffeineStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_CaffeineStorageRefillInformation)],
      [_CaffeineStorageRefillResult],
      [],
    ),
  '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addAdVideo' : IDL.Func([IDL.Text, ExternalBlob, IDL.Bool], [AdVideoId], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'assignOrderToAgent' : IDL.Func([OrderId, DeliveryAgentId], [], []),
  'createCategory' : IDL.Func([IDL.Text], [CategoryId], []),
  'createDeliveryAgent' : IDL.Func([IDL.Text, IDL.Text], [DeliveryAgentId], []),
  'createProduct' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Nat, CategoryId, IDL.Nat, ExternalBlob],
      [ProductId],
      [],
    ),
  'deleteProduct' : IDL.Func([ProductId], [], []),
  'getActiveAdVideos' : IDL.Func([], [IDL.Vec(AdVideo)], ['query']),
  'getAdVideos' : IDL.Func([], [IDL.Vec(AdVideo)], ['query']),
  'getAllProducts' : IDL.Func([], [IDL.Vec(Product)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getCategories' : IDL.Func([], [IDL.Vec(Category)], ['query']),
  'getDeliveryAgents' : IDL.Func([], [IDL.Vec(DeliveryAgent)], ['query']),
  'getOrder' : IDL.Func([OrderId], [Order], ['query']),
  'getOrdersByPhone' : IDL.Func([IDL.Text], [IDL.Vec(Order)], ['query']),
  'getProduct' : IDL.Func([ProductId], [Product], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'placeOrder' : IDL.Func(
      [
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Vec(OrderItem),
        IDL.Nat,
        IDL.Variant({
          'cod' : IDL.Null,
          'upi' : IDL.Record({ 'transactionId' : IDL.Text }),
        }),
      ],
      [OrderId],
      [],
    ),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'updateOrderStatus' : IDL.Func([OrderId, OrderStatus], [], []),
  'updateProduct' : IDL.Func(
      [
        ProductId,
        IDL.Text,
        IDL.Text,
        IDL.Nat,
        CategoryId,
        IDL.Nat,
        ExternalBlob,
      ],
      [],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _CaffeineStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _CaffeineStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _CaffeineStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const ExternalBlob = IDL.Vec(IDL.Nat8);
  const AdVideoId = IDL.Nat;
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const OrderId = IDL.Nat;
  const DeliveryAgentId = IDL.Nat;
  const CategoryId = IDL.Nat;
  const ProductId = IDL.Nat;
  const AdVideo = IDL.Record({
    'id' : AdVideoId,
    'title' : IDL.Text,
    'active' : IDL.Bool,
    'video' : ExternalBlob,
  });
  const Product = IDL.Record({
    'id' : ProductId,
    'name' : IDL.Text,
    'description' : IDL.Text,
    'stock' : IDL.Nat,
    'category' : CategoryId,
    'image' : ExternalBlob,
    'price' : IDL.Nat,
  });
  const UserProfile = IDL.Record({
    'name' : IDL.Text,
    'address' : IDL.Text,
    'phone' : IDL.Text,
  });
  const Category = IDL.Record({ 'id' : CategoryId, 'name' : IDL.Text });
  const DeliveryAgent = IDL.Record({
    'id' : DeliveryAgentId,
    'name' : IDL.Text,
    'phone' : IDL.Text,
  });
  const OrderStatus = IDL.Variant({
    'shipped' : IDL.Null,
    'cancelled' : IDL.Null,
    'pending' : IDL.Null,
    'outForDelivery' : IDL.Null,
    'delivered' : IDL.Null,
    'confirmed' : IDL.Null,
    'processing' : IDL.Null,
  });
  const Time = IDL.Int;
  const OrderItem = IDL.Record({
    'productId' : ProductId,
    'quantity' : IDL.Nat,
    'price' : IDL.Nat,
  });
  const Order = IDL.Record({
    'id' : OrderId,
    'customerName' : IDL.Text,
    'status' : OrderStatus,
    'paymentMethod' : IDL.Variant({
      'cod' : IDL.Null,
      'upi' : IDL.Record({ 'transactionId' : IDL.Text }),
    }),
    'customerPhone' : IDL.Text,
    'createdAt' : Time,
    'totalAmount' : IDL.Nat,
    'address' : IDL.Text,
    'items' : IDL.Vec(OrderItem),
    'deliveryAgent' : IDL.Opt(DeliveryAgentId),
  });
  
  return IDL.Service({
    '_caffeineStorageBlobIsLive' : IDL.Func(
        [IDL.Vec(IDL.Nat8)],
        [IDL.Bool],
        ['query'],
      ),
    '_caffeineStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_caffeineStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_CaffeineStorageCreateCertificateResult],
        [],
      ),
    '_caffeineStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_CaffeineStorageRefillInformation)],
        [_CaffeineStorageRefillResult],
        [],
      ),
    '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addAdVideo' : IDL.Func(
        [IDL.Text, ExternalBlob, IDL.Bool],
        [AdVideoId],
        [],
      ),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'assignOrderToAgent' : IDL.Func([OrderId, DeliveryAgentId], [], []),
    'createCategory' : IDL.Func([IDL.Text], [CategoryId], []),
    'createDeliveryAgent' : IDL.Func(
        [IDL.Text, IDL.Text],
        [DeliveryAgentId],
        [],
      ),
    'createProduct' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Nat, CategoryId, IDL.Nat, ExternalBlob],
        [ProductId],
        [],
      ),
    'deleteProduct' : IDL.Func([ProductId], [], []),
    'getActiveAdVideos' : IDL.Func([], [IDL.Vec(AdVideo)], ['query']),
    'getAdVideos' : IDL.Func([], [IDL.Vec(AdVideo)], ['query']),
    'getAllProducts' : IDL.Func([], [IDL.Vec(Product)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getCategories' : IDL.Func([], [IDL.Vec(Category)], ['query']),
    'getDeliveryAgents' : IDL.Func([], [IDL.Vec(DeliveryAgent)], ['query']),
    'getOrder' : IDL.Func([OrderId], [Order], ['query']),
    'getOrdersByPhone' : IDL.Func([IDL.Text], [IDL.Vec(Order)], ['query']),
    'getProduct' : IDL.Func([ProductId], [Product], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'placeOrder' : IDL.Func(
        [
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Vec(OrderItem),
          IDL.Nat,
          IDL.Variant({
            'cod' : IDL.Null,
            'upi' : IDL.Record({ 'transactionId' : IDL.Text }),
          }),
        ],
        [OrderId],
        [],
      ),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'updateOrderStatus' : IDL.Func([OrderId, OrderStatus], [], []),
    'updateProduct' : IDL.Func(
        [
          ProductId,
          IDL.Text,
          IDL.Text,
          IDL.Nat,
          CategoryId,
          IDL.Nat,
          ExternalBlob,
        ],
        [],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };